import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./Components/TopBar/page";
import Navbar from "./Components/Navbar/page";
import Footer from "./Components/Footer/page";
import BottomBar from "./Components/BottomBar/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <TopBar/>
        <Navbar/>
        {children}
        <Footer/>
        <BottomBar/>
      </body>
    </html>
  );
}
